### ISSUE TITLE
Why is the url converted from https to http?

### ISSUE THREAD

**Issue by twistedpixel** [iSenseLabs/OpenCartAPI#6]
Is there a reason to do this?

**Comment by raxbg** [comment]
Line 366 seems to be what you are looking for. https://github.com/iSenseLabs/OpenCartAPI/blob/9fb82034cd6cca326742b4d060d5c4dc4fb33b3a/opencart.php#L366

The only reason for this being there is to make sure that the provided URL has a protocol, but forcing HTTP is definitely not the best thing to do. Please try replacing line 366 with this:
 `$this->url = (!preg_match('/^https?\:\/\//', $url) ? 'http://' : '') . rtrim($url, '/') . '/index.php?';`.

Let me know if everything is okay, so I can push an update.

**Comment by twistedpixel** [comment]
That's almost exactly what I changed in my local file so go ahead and push that out as it's been working fine for a week or so. Thanks!
